---
# handlers file for tinc

#- name: Restart Service
#  service:
#    name: "{{ service_name }}"
#    daemon_reload: "{{ ansible_service_mgr == 'systemd' | ternary('yes',omit) }}"
#    state: restarted

- name: Restart Service
  systemd:
   daemon_reload: yes
  when: ansible_service_mgr == "systemd"

- name: Restart Service
  service:
    name: "{{ service_name }}"
    state: restarted
